### ISSUE TITLE
I need to contact you.

### ISSUE THREAD

**Issue by HenriqueDoura** [cp3hnu/CPImageViewer#1]
where can I find your twitter or email? I'm having an issue with this pod, I'm on Xcode 7.3 and using Swift 2.2.

**Comment by cp3hnu** [comment]
cp3hnu@gmail.com in my homepage.

**Comment by HenriqueDoura** [comment]
Hello, good evening. I'm Henrique and I've tried to implement your pod in
my project but I can't figure out how to use it. Do you have an example
project?

Please help me, I loved the animations and really need it in my app, you
did a really good job on this one!!

Thanks in advance!

Best regards,
Henrique Dourado

**Comment by cp3hnu** [comment]
You are welcome. Yes, I have a example project and sent it to you email. You can also the pod in you project.
1. Go to you project folder
$ cd project_folder
2. Initialize pod or create a podfile  
$ pod init
3. Open the .podfile file
4. Uncomment the "platform :ios, '8.0' and "use_frameworks!". Then add "pod 'CPImageViewer'"
5. Install pod
    $ pod install
6. Open workspace(.xcworkspace)
You can use the pod by importing module("import CPImageViewer").
You can contact me if you have any questions.

**Comment by cp3hnu** [comment]
You are welcome. This is example project.  I hope that would be useful for
you. You can contact me if you have any questions.

2016-03-29 7:02 GMT+08:00 Henrique Dourado <notifications@github.com>:

**Comment by HenriqueDoura** [comment]
I know how to implement it, my problem is when I try to use it. Like when I try to assign an image to the UIImageView.image, it's crashing saying that it found nil

**Comment by cp3hnu** [comment]
I don't known your problem. You can refer to the example project I sent to you email.

**Comment by HenriqueDoura** [comment]
I managed to make it work. There's a bug tho. If I tap the image, close it
and tap it again, the image view dissppears

Em terça-feira, 29 de março de 2016, Wei Zhao notifications@github.com
escreveu:

**Comment by cp3hnu** [comment]
I haven't met. Can you send me your project?

**Comment by HenriqueDoura** [comment]
It was fixed already

Em quarta-feira, 13 de abril de 2016, Wei Zhao notifications@github.com
escreveu:
