### ISSUE TITLE
problem installing version 4.0.0

### ISSUE THREAD

**Issue by Adarkas2302** [cp3hnu/CPImageViewer#2]
I can't get the version that supports swift 3.0 to download. Only getting version 3.1.0 and when i specify the version as 4.0.0 i get an error.

```
[!] Unable to satisfy the following requirements:
- `CPImageViewer (= 4.0.0)` required by `Podfile`
None of your spec sources contain a spec satisfying the dependency: `CPImageViewer (= 4.0.0)`.
```

**Comment by cp3hnu** [comment]
CocoaPod had a problem. Please wait a moment.

**Comment by cp3hnu** [comment]
V4.0.0 re-written by Swift 3 is available in Cocoapod.

**Comment by Adarkas2302** [comment]
Sorry for the late response. It does work now.
